### ISSUE TITLE
Official support?

### ISSUE THREAD

**Issue by 4kimov** [paolo-rossi/sqids-delphi#1]
Hi @paolo-rossi,

Just discovered your repo, wanted to see if you'd be interested in moving this to the official [Sqids org](https://github.com/sqids/) so that more people can discover and use Delphi/Pascal version?

**Comment by paolo-rossi** [comment]
Hello Ivan,

yes absolutely, in fact I was going to ask you the same question :-)

do you need something from me in order to publish on the sqids page?

Ciao,
Paolo.

**Comment by 4kimov** [comment]
Hi @paolo-rossi, great!

Yeah, there's a few steps to do (some for you, some for me).

The first is to move the repository so it's available at `https://github.com/sqids/sqids-delphi`. We can do this one of two ways. I typically create a blank template repo in the Sqids org, and then the maintainer does a PR with the initial code. But since your repo already has existing stars/forks, I suggest you try transferring it to the [Sqids](https://github.com/sqids) org. Whichever way you pick, I'll send you maintainer rights so you can push/manage whatever is needed. Alternatively, if you'd like to start over with a blank repo, that's also fine - just let me know so I can create it.

After that, I can create an initial issue (with a few minor cleanup items), and once it's good to go - I'll update the website. That's should be it 👍

**Comment by 4kimov** [comment]
Hi @paolo-rossi,

Haven't heard from you in a while. We have a [Pascal version](https://sqids.org/pascal) implemented on the site now, so don't think we need to transfer this repo anymore.

Please let me know if you'd like to be added as a maintainer to the new repo.

**Comment by paolo-rossi** [comment]
Hello Ivan,

> Haven't heard from you in a while. 
A few days of vacation for Christmas...

> We have a [Pascal version](https://sqids.org/pascal)
I see, well mine is specifically for Delphi so unless you want to add a Delphi repo I think I will maintain my version.

Ciao,
Paolo.

**Comment by 4kimov** [comment]
Hi @paolo-rossi,

All good. The Pascal version is for both Delphi and Free Pascal; I'd be more than happy to send you a maintainer invite; I think no matter the language/repo, there's always improvements, cleanup, bug fixes, random todos, etc.

I'll close the issue for now, but let me know if you'd like the invite, we could always use more help.
